### 시작하기

In [1]:
# Tensor
# Tensor는 Numpy의 ndarrays와 비슷하며, 추가적으로 계산을 빠르게 하기 위해 GPU/MPS에서 사용이 가능합니다.
from __future__ import print_function
import torch

### Note
##### 초기화되지 않은 행렬이 선언되지 않았지만, 사용하기 전에  정확하게 알려진 값들을 포함하지 않습니다.
##### 초기화되지 않은 행렬이 생성 되었을 때, 그때 메모리에 할당된 어떤 값이든지 초기 값으로 나타날 것입니다.


In [3]:
# 초기화되지 않은 5x3 행렬 선언
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 임의적으로 초기화된 행렬 생성
x = torch.randn(5, 3)
print(x)

tensor([[ 2.1263, -1.4520, -0.6851],
        [ 0.7791,  0.9374, -1.2152],
        [ 0.5625,  0.0032, -0.1199],
        [ 0.5409, -0.4640, -0.1520],
        [ 0.4223,  0.4172, -0.8257]])


In [5]:
# 데이터 타입이 long인 0 행렬 생성
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# data로부터 직접 tensor 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# 기존에 존재하는 tensor에 기반한 tensor 생성하기
# 이 메소드는 유저에 의해 새로운 값들이 제공되지 않는다면, 입력 tensor의 성질들을 재사용 합니다. (e.g. dtype)
x = x.new_ones(5, 3, dtype=torch.double) # new_* 메소드는 크기를 받는다.
print(x)

x = torch.randn_like(x, dtype=torch.float) # dtype override!
print(x)                                   # 결과는 동일한 크기를 갖는다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.2708e-01,  1.0495e+00, -1.2772e+00],
        [-1.6085e+00,  9.6866e-01, -1.2473e+00],
        [-9.3765e-01,  1.5851e+00, -6.9355e-01],
        [-1.0415e+00,  5.8110e-01,  9.4333e-04],
        [-1.5533e+00, -3.3842e-01, -6.4799e-01]])


In [8]:
# 행렬 사이즈 검출
print(x.size())

torch.Size([5, 3])


### Note
##### torch.Size는 튜플입니다.
##### 따라서 튜플 연산을 지원합니다.

### 연산 - Operations
##### 연산에는 다양한 문법들이 있습니다.
##### 다음의 예제에서 덧셈 연산을 살펴보겠습니다.



In [9]:
# 덧셈 : 문법 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.9848,  1.9424, -0.7776],
        [-1.0540,  1.4525, -1.2175],
        [-0.6127,  2.2301, -0.3827],
        [-0.4101,  1.4889,  0.9433],
        [-1.1567,  0.0761,  0.1039]])


In [10]:
# 덧셈 : 문법 2
print(torch.add(x, y))

tensor([[ 0.9848,  1.9424, -0.7776],
        [-1.0540,  1.4525, -1.2175],
        [-0.6127,  2.2301, -0.3827],
        [-0.4101,  1.4889,  0.9433],
        [-1.1567,  0.0761,  0.1039]])


In [11]:
# 덧셈 : 결과 tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9848,  1.9424, -0.7776],
        [-1.0540,  1.4525, -1.2175],
        [-0.6127,  2.2301, -0.3827],
        [-0.4101,  1.4889,  0.9433],
        [-1.1567,  0.0761,  0.1039]])


In [12]:
# 덧셈 : in-place
# (별도의 보조 데이터 구조를 사용하지 않고 입력값 input을 변환하는 알고리즘, 교체 또는 교환을 통해서만 업데이트)

# x를 y에 더하기
y.add_(x)
print(y)

tensor([[ 0.9848,  1.9424, -0.7776],
        [-1.0540,  1.4525, -1.2175],
        [-0.6127,  2.2301, -0.3827],
        [-0.4101,  1.4889,  0.9433],
        [-1.1567,  0.0761,  0.1039]])


### Note
##### in-place로 tensor를 변형하는 연산은 뒤에 _가 붙습니다.
##### 예를 들어 x.copy_(y), x.t_()는 x를 변환합니다


In [13]:
# Numpy와 같은 indexing 표기법을 사용할 수 있습니다.
print(x[:,1])

tensor([ 1.0495,  0.9687,  1.5851,  0.5811, -0.3384])


In [15]:
# 크기 조정 : tensor를 resize/reshape하고 싶으면 torch.view를 사용할 수 있습니다.
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # 크기 -1은 다른 차원으로부터 추론됩니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
# 하나의 원소로 구성된 tensor를 갖고 있다면, 숫자 값을 얻기 위해 .item()를 사용합니다.
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0460])
-1.045987606048584


### 추후에 읽을 거리

##### 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학적인 연산, 선형대수학, 난수(random number) 등을 포함한 100가지 이상의 Tensor 연산을 아래 기술되어 있습니다.
##### https://pytorch.org/docs/stable/torch.html