### NumPy 변환(Bridge)
##### Torch Tensor를 Numpy 배열로 전환하거나 그 반대도 가능합니다.
##### (만약 Torch Tensor가 CPU에 있으면) Torch Tensor와 NumPy 배열은 기본 메모리 공간을 공유할 것입니다.
##### 그리고 하나를 변환하는 것은 다른 것도 변환합니다.

In [1]:
import torch

In [2]:
# Torch Tensor를 NumPy로 변환
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [3]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [4]:
# 어떻게 numpy 배열 값이 변경되는지 확인하기
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# a에 1을 더해줬더니 b의 값도 변경되었습니다.

### NumPy Array를 Torch Tensor로 변환하기
##### np array를 변경하면 어떻게 Torch Tensor의 값도 자동으로 변경되는지 확인하기

In [5]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


##### CharTensor를 제외한 CPU에 있는 모든 Tensor는 NumPy로 변환과 반대도 지원합니다.

### CUDA Tensors
##### Tensor는 .to 메서드를 사용해서 어떤 장치로 이동될 수 있습니다.

In [9]:
# 만약 CUDA를 이용 가능할 때만, 이 cell를 작동시킬 수 있습니다.
# tensor를 GPU에서 꺼내고 넣기 위해 ''torch.device'' 객체를 사용할 것입니다.

x = torch.randn(5, 3)
if torch.cuda.is_available():
    device = torch.device('cuda')         # CUDA 장치 객체
    y = torch.ones_like(x, device=device) # GPU에 tensor를 직접 생성
    x = x.to(device)                      # 또는 ''.to('cuda')''를 이용하기
    
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))      # ''.to''는 dtype까지 함께 변경 가능

In [ ]:
# cuda 사용이 불가능하기 때문에 if문을 통과하지 못해 결과가 출력되지 않는다.